/******************************************************************************
 * Copyright (c), AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_test_LampManagerCallbackTest */

#ifndef _Included_org_allseen_lsf_test_LampManagerCallbackTest
#define _Included_org_allseen_lsf_test_LampManagerCallbackTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getAllLampIDsReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getAllLampIDsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampNameReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    setLampNameReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_setLampNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampManufacturerReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampManufacturerReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    lampsFoundCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_lampsFoundCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    lampsLostCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_lampsLostCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampParametersEnergyUsageMilliwattsFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampParametersEnergyUsageMilliwattsFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    lampNameChangedCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_lampNameChangedCB
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampDetailsReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampDetails;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampDetailsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampParametersReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampParameters;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampParametersReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampParametersLumensFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampParametersLumensFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jboolean);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    pulseLampWithStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_pulseLampWithStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    pulseLampWithPresetReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_pulseLampWithPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampServiceVersionReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampServiceVersionReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateToPresetReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateToPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampSupportedLanguagesReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampSupportedLanguagesReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    setLampEffectReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_setLampEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampState;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    lampStateChangedCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Ljava/lang/String;Lorg/allseen/lsf/LampState;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_lampStateChangedCB
  (JNIEnv *, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampFaultsReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampFaultsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlongArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    clearLampFaultReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_clearLampFaultReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
