/******************************************************************************
 * Copyright (c), AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_test_PulseEffectManagerCallbackTest */

#ifndef _Included_org_allseen_lsf_test_PulseEffectManagerCallbackTest
#define _Included_org_allseen_lsf_test_PulseEffectManagerCallbackTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    getPulseEffectReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/PulseEffect;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_getPulseEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    applyPulseEffectOnLampsReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_applyPulseEffectOnLampsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    applyPulseEffectOnLampGroupsReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_applyPulseEffectOnLampGroupsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    getAllPulseEffectIDsReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_getAllPulseEffectIDsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    getPulseEffectNameReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_getPulseEffectNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    setPulseEffectNameReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_setPulseEffectNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    createPulseEffectReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_createPulseEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    pulseEffectsNameChangedCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_pulseEffectsNameChangedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    pulseEffectsCreatedCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_pulseEffectsCreatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    pulseEffectsUpdatedCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_pulseEffectsUpdatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    pulseEffectsDeletedCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_pulseEffectsDeletedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    updatePulseEffectReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_updatePulseEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_PulseEffectManagerCallbackTest
 * Method:    deletePulseEffectReplyCB
 * Signature: (Lorg/allseen/lsf/PulseEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PulseEffectManagerCallbackTest_deletePulseEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
