/******************************************************************************
 * Copyright (c), AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_test_TransitionEffectManagerCallbackTest */

#ifndef _Included_org_allseen_lsf_test_TransitionEffectManagerCallbackTest
#define _Included_org_allseen_lsf_test_TransitionEffectManagerCallbackTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    getTransitionEffectReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/TransitionEffect;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_getTransitionEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    applyTransitionEffectOnLampsReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_applyTransitionEffectOnLampsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    applyTransitionEffectOnLampGroupsReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_applyTransitionEffectOnLampGroupsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    getAllTransitionEffectIDsReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_getAllTransitionEffectIDsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    getTransitionEffectNameReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_getTransitionEffectNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    setTransitionEffectNameReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_setTransitionEffectNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    transitionEffectsNameChangedCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_transitionEffectsNameChangedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    createTransitionEffectReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_createTransitionEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    transitionEffectsCreatedCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_transitionEffectsCreatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    updateTransitionEffectReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_updateTransitionEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    transitionEffectsUpdatedCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_transitionEffectsUpdatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    deleteTransitionEffectReplyCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_deleteTransitionEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_TransitionEffectManagerCallbackTest
 * Method:    transitionEffectsDeletedCB
 * Signature: (Lorg/allseen/lsf/TransitionEffectManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_TransitionEffectManagerCallbackTest_transitionEffectsDeletedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
