/******************************************************************************
 * Copyright (c), AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_test_PresetManagerCallbackTest */

#ifndef _Included_org_allseen_lsf_test_PresetManagerCallbackTest
#define _Included_org_allseen_lsf_test_PresetManagerCallbackTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    getAllPresetIDsReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_getAllPresetIDsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    getPresetReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampState;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_getPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    getPresetNameReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_getPresetNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    setPresetNameReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_setPresetNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    presetsNameChangedCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_presetsNameChangedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    createPresetReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_createPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    presetsCreatedCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_presetsCreatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    updatePresetReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_updatePresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    presetsUpdatedCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_presetsUpdatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    deletePresetReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_deletePresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    presetsDeletedCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_presetsDeletedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    getDefaultLampStateReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;Lorg/allseen/lsf/LampState;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_getDefaultLampStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    setDefaultLampStateReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_setDefaultLampStateReplyCB
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    defaultLampStateChangedCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_defaultLampStateChangedCB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_test_PresetManagerCallbackTest
 * Method:    createPresetWithTrackingReplyCB
 * Signature: (Lorg/allseen/lsf/PresetManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_PresetManagerCallbackTest_createPresetWithTrackingReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
