/******************************************************************************
 * Copyright (c), AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_test_LampGroupManagerCallbackTest */

#ifndef _Included_org_allseen_lsf_test_LampGroupManagerCallbackTest
#define _Included_org_allseen_lsf_test_LampGroupManagerCallbackTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    getAllLampGroupIDsReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_getAllLampGroupIDsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    getLampGroupNameReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_getLampGroupNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    setLampGroupNameReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_setLampGroupNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    getLampGroupReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampGroup;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_getLampGroupReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    lampGroupsNameChangedCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_lampGroupsNameChangedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    lampGroupsUpdatedCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_lampGroupsUpdatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    createLampGroupReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_createLampGroupReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    lampGroupsCreatedCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_lampGroupsCreatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    deleteLampGroupReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_deleteLampGroupReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    lampGroupsDeletedCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_lampGroupsDeletedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    pulseLampGroupWithStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_pulseLampGroupWithStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    pulseLampGroupWithPresetReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_pulseLampGroupWithPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    updateLampGroupReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_updateLampGroupReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateToPresetReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateToPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    createLampGroupWithTrackingReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_createLampGroupWithTrackingReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    setLampGroupEffectReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_setLampGroupEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
