# Contributed by Qualcomm Connected Experiences, Inc.,
# with authorization from the AllSeen Alliance, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Pursuant to Section 1 of the License, the work of authorship constituting
# a Work and any Contribution incorporated in the Work shall mean only that
# Contributor's code submissions authored by that Contributor.  Any rights
# granted under the License are conditioned upon acceptance of these
# clarifications.

Import('contsenv')

srcs = contsenv.Glob('*.cc')
contsenv.Append(CPPPATH = contsenv.Dir('$APP_COMMON_DIR/cpp/samples_common').srcnode())
libs = []

# Static library
objs = contsenv.Object(srcs)
libs.append(contsenv.StaticLibrary('alljoyn_media_content', objs))

# Shared library
if contsenv.get('LIBTYPE', 'static') != 'static':
    shobjs = contsenv.SharedObject(srcs)
    libs.append(contsenv.SharedLibrary('alljoyn_media_content', shobjs))

Return('libs')
