#!/bin/sh
#
# Copyright (c) 2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

MY_CWD=$(dirname $0)

# 1st priority: from environment variable
MY_VALUE=$(eval $(echo echo \$\{$1\}))

# 2nd priority: from project file
if [ "${MY_VALUE}" = "" ]; then
  if [ $(grep -c "<name>$1" "${MY_CWD}/.project") -gt 0 ]; then
    MY_VALUE=$(xmllint --xpath "//variable[name='$1']/value" ${MY_CWD}/.project | sed -e "s:<value>::g" -e "s:</value>::g" -e "s:%7[Bb]:{:g" -e "s:%7[Dd]:}:g" -e "s:${PROJECT_LOC}:${MY_CWD}/..:g" -e "s/^file://g")
  fi
fi

# 3rd priority: from workspace path
if [ "${MY_VALUE}" = "" ]; then
  if [ "$2" != "" ]; then
    MY_VALUE=$(grep "pathvariable.$1=" < "$2/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.core.resources.prefs" | sed -e "s:pathvariable.[^=]*=::")
  fi
fi

# 4th priority: LuminaireSetup.sh legacy folder structure
if [ "${MY_VALUE}" = "" ]; then
  if [ "$1" = "L_AJTCL" ]; then
    MY_VALUE=${MY_CWD}/../../../../../ajtcl
  fi
  if [ "$1" = "L_ALLJOYN" ]; then
    MY_VALUE=${MY_CWD}/../../../../../alljoyn
  fi
  if [ "$1" = "L_BASE" ]; then
    MY_VALUE=${MY_CWD}/../../../../../base
  fi
  if [ "$1" = "L_BASE_TCL" ]; then
    MY_VALUE=${MY_CWD}/../../../../../base_tcl
  fi
  if [ "$1" = "L_SERVICE" ]; then
    MY_VALUE=${MY_CWD}/../../../../../service_framework
  fi
  if [ "$1" = "OPENSSL_HOME" ]; then
    MY_VALUE=${MY_CWD}/jni/openssl-1.0.1f
  fi
fi

# Handle parent path components
MY_COUNT=$(echo -n ${MY_VALUE} | sed -e "s:^\${PARENT-\([0-9]*\)-PROJECT_LOC}.*:\1:" | sed -e "s:^\([0-9]*\).*:\1:")

if [ -n "${MY_COUNT}" ] && [ "${MY_COUNT}" -gt "0" ]; then
  for n in $(seq 1 ${MY_COUNT}); do
    MY_PREFIX=${MY_PREFIX}../
  done

  MY_VALUE=$(echo ${MY_VALUE} | sed -e "s:^\${PARENT-\([0-9]*\)-PROJECT_LOC}/:${MY_PREFIX}:")
fi

echo ${MY_VALUE}

