#!/bin/sh /etc/rc.common

# Copyright (c) 2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
#

START=75
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_SIG_STOP="INT"

boot() {
	start
}

start() {
	service_start /usr/bin/alljoyn-gwagent --gwagent-policy-file=/etc/alljoyn/gwagent/gwagent.conf --apps-policy-dir=/etc/alljoyn/gwagent-apps
}

stop() {
	service_stop /usr/bin/alljoyn-gwagent
}
