# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
# 
import os.path
Import('env')
 
sdk_methodsClient_sample = env.Java('$OBJDIR_ALLJOYN_JAVA/samples/JavaSDKDoc/JavaSDKDocAboutClient', 'src',
                                    JAVACLASSPATH=env.GetBuildPath(env.subst('$JARDIR/alljoyn.jar')))
    
sdk_methodsClient_sample.append('MANIFEST.MF')

env.Jar('$JARDIR/JavaSDKDocAboutClient.jar', sdk_methodsClient_sample)
env.Requires(sdk_methodsClient_sample, '$JARDIR/alljoyn.jar')

#add the sample to the dist with out adding the build files.
# The return value is the collection of files installed in the build destination.
returnValue = env.Install('$JAVA_DISTDIR/samples/JavaSDKDoc/JavaSDKDocAboutClient', ['src', '.classpath', '.project'])

#clean up the created manifest file
# env.Clean('.', sdk_methodsClient_sample)
#clean the build folder that remains after cleaning all other files.
env.Clean('.', 'build')

Return('returnValue')
