# Contributed by Qualcomm Connected Experiences, Inc.,
# with authorization from the AllSeen Alliance, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Pursuant to Section 1 of the License, the work of authorship constituting
# a Work and any Contribution incorporated in the Work shall mean only that
# Contributor's code submissions authored by that Contributor.  Any rights
# granted under the License are conditioned upon acceptance of these
# clarifications.
import os

Import('env')

config_env = env.Clone()

config_env.Append(CPPDEFINES = {
    'AJ_MAIN': None,
    'AJ_NUM_REPLY_CONTEXTS': '8',
    'AJ_MAX_OBJECT_LISTS': '9',
    'ANNOUNCE_BASED_DISCOVERY': '1',
    'CONFIG_SERVICE': '1'
})

config_env.Append(LIBPATH = '#dist/lib')
config_env.Prepend(LIBS = ['ajtcl_services_config'])
config_env.Prepend(LIBS = ['ajtcl'])

common_objs = config_env.Glob('../../common/config/src/*' + env['OBJSUFFIX'])
config_objs = config_env.Object(config_env.Glob('*.c'))
config_progs = config_env.Program('ConfigSample', common_objs + config_objs)

config_env.Install('#dist/bin/services', config_progs)
