# Contributed by Qualcomm Connected Experiences, Inc.,
# with authorization from the AllSeen Alliance, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Pursuant to Section 1 of the License, the work of authorship constituting
# a Work and any Contribution incorporated in the Work shall mean only that
# Contributor's code submissions authored by that Contributor.  Any rights
# granted under the License are conditioned upon acceptance of these
# clarifications.
import os

Import('env')

src_env = env.Clone()

srcs = []
srcs.extend(src_env.Glob('common/*.c'))
srcs.extend(src_env.Glob('config/*.c'))
#srcs.extend(src_env.Glob('controlpanel/*.c'))
#srcs.extend(src_env.Glob('controlpanel/Common/*.c'))
#srcs.extend(src_env.Glob('controlpanel/Widgets/*.c'))
srcs.extend(src_env.Glob('notification/*.c'))
if src_env['enable_onboarding']:
    srcs.extend(src_env.Glob('onboarding/*.c'))
#srcs.extend(src_env.Glob('time/*.c'))

objs = src_env.Object(srcs)
lib = src_env.Library("ajtcl_services", objs)
src_env.Install("#dist/lib", lib)

if src_env['build_shared']:
    objs = src_env.SharedObject(srcs)
    lib = src_env.SharedLibrary("ajtcl_services", objs)
    src_env.Install("#dist/lib", lib)

