# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
# 

import os
import string
Import('env')

# AllJoyn Java binding
# enable UTF-8 character in unit tests
env.Append(JAVACFLAGS = ['-encoding', 'UTF-8'])
test_classes = env.Java('$OBJDIR_ALLJOYN_JAVA/test/classes', '.', JAVACLASSPATH=os.pathsep.join(
        [env['JAVACLASSPATH'], env.GetBuildPath(env.subst('$JARDIR/alljoyn.jar'))]))

# The return value is the collection of files installed in the build destination.
returnValue = env.Jar('$JARDIR/alljoyn_test.jar', test_classes)
env.Requires(test_classes, '$JARDIR/alljoyn.jar')

Return('returnValue')
