/******************************************************************************
 * Copyright AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_TransitionEffectV2 */

#ifndef _Included_org_allseen_lsf_TransitionEffectV2
#define _Included_org_allseen_lsf_TransitionEffectV2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_TransitionEffectV2
 * Method:    setLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_TransitionEffectV2_setLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_TransitionEffectV2
 * Method:    getLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_TransitionEffectV2_getLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_TransitionEffectV2
 * Method:    setPresetID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_TransitionEffectV2_setPresetID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_TransitionEffectV2
 * Method:    getPresetID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_TransitionEffectV2_getPresetID
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_TransitionEffectV2
 * Method:    setTransitionPeriod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_TransitionEffectV2_setTransitionPeriod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_TransitionEffectV2
 * Method:    getTransitionPeriod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_TransitionEffectV2_getTransitionPeriod
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_TransitionEffectV2
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_TransitionEffectV2_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_TransitionEffectV2
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_TransitionEffectV2_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
