/******************************************************************************
 * Copyright (c) 2014, AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_PresetManager */

#ifndef _Included_org_allseen_lsf_PresetManager
#define _Included_org_allseen_lsf_PresetManager
#ifdef __cplusplus
extern "C" {
#endif
#undef org_allseen_lsf_PresetManager_MAX_PRESETS
#define org_allseen_lsf_PresetManager_MAX_PRESETS 100L
/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    getAllPresetIDs
 * Signature: ()Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_getAllPresetIDs
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    getPreset
 * Signature: (Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_getPreset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    getPresetName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_getPresetName
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    setPresetName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_setPresetName
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    createPreset
 * Signature: (Lorg/allseen/lsf/LampState;Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_createPreset
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    updatePreset
 * Signature: (Ljava/lang/String;Lorg/allseen/lsf/LampState;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_updatePreset
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    deletePreset
 * Signature: (Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_deletePreset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    getDefaultLampState
 * Signature: ()Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_getDefaultLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    setDefaultLampState
 * Signature: (Lorg/allseen/lsf/LampState;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_setDefaultLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    createPresetWithTracking
 * Signature: (Lorg/allseen/lsf/sdk/TrackingID;Lorg/allseen/lsf/LampState;Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_createPresetWithTracking
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    getPresetDataSet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PresetManager_getPresetDataSet
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    createNativeObject
 * Signature: (Lorg/allseen/lsf/ControllerClient;Lorg/allseen/lsf/PresetManagerCallback;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetManager_createNativeObject
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PresetManager
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetManager_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
