/******************************************************************************
 * Copyright AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_SceneWithSceneElements */

#ifndef _Included_org_allseen_lsf_SceneWithSceneElements
#define _Included_org_allseen_lsf_SceneWithSceneElements
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_SceneWithSceneElements
 * Method:    setSceneElements
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_SceneWithSceneElements_setSceneElements
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_SceneWithSceneElements
 * Method:    getSceneElements
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_SceneWithSceneElements_getSceneElements
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_SceneWithSceneElements
 * Method:    isDependentOnSceneElement
 * Signature: (Ljava/lang/String;)Lorg/allseen/lsf/sdk/ResponseCode;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_SceneWithSceneElements_isDependentOnSceneElement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_SceneWithSceneElements
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_SceneWithSceneElements_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_SceneWithSceneElements
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_SceneWithSceneElements_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_SceneWithSceneElements
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_SceneWithSceneElements_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
