/******************************************************************************
 * Copyright (c) 2014, AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_Scene */

#ifndef _Included_org_allseen_lsf_Scene
#define _Included_org_allseen_lsf_Scene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_Scene
 * Method:    setStateTransitionEffects
 * Signature: ([Lorg/allseen/lsf/StateTransitionEffect;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_Scene_setStateTransitionEffects
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    getStateTransitionEffects
 * Signature: ()[Lorg/allseen/lsf/StateTransitionEffect;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_Scene_getStateTransitionEffects
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    setPresetTransitionEffects
 * Signature: ([Lorg/allseen/lsf/PresetTransitionEffect;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_Scene_setPresetTransitionEffects
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    getPresetTransitionEffects
 * Signature: ()[Lorg/allseen/lsf/PresetTransitionEffect;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_Scene_getPresetTransitionEffects
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    setStatePulseEffects
 * Signature: ([Lorg/allseen/lsf/StatePulseEffect;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_Scene_setStatePulseEffects
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    getStatePulseEffects
 * Signature: ()[Lorg/allseen/lsf/StatePulseEffect;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_Scene_getStatePulseEffects
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    setPresetPulseEffects
 * Signature: ([Lorg/allseen/lsf/PresetPulseEffect;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_Scene_setPresetPulseEffects
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    getPresetPulseEffects
 * Signature: ()[Lorg/allseen/lsf/PresetPulseEffect;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_Scene_getPresetPulseEffects
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_Scene_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_Scene_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_Scene
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_Scene_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
