/******************************************************************************
 * Copyright (c) 2014, AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_StatePulseEffect */

#ifndef _Included_org_allseen_lsf_StatePulseEffect
#define _Included_org_allseen_lsf_StatePulseEffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    setLamps
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_setLamps
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    getLamps
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_StatePulseEffect_getLamps
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    setLampGroups
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_setLampGroups
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    getLampGroups
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_StatePulseEffect_getLampGroups
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    setPulsePeriod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_setPulsePeriod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    getPulsePeriod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_StatePulseEffect_getPulsePeriod
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    setPulseDuration
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_setPulseDuration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    getPulseDuration
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_StatePulseEffect_getPulseDuration
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    setPulseCount
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_setPulseCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    getPulseCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_StatePulseEffect_getPulseCount
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    setFromLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_setFromLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    getFromLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_StatePulseEffect_getFromLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    setToLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_setToLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    getToLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_StatePulseEffect_getToLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_StatePulseEffect_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_StatePulseEffect
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_StatePulseEffect_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
