/******************************************************************************
 * Copyright (c) AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_PulseEffectManager */

#ifndef _Included_org_allseen_lsf_PulseEffectManager
#define _Included_org_allseen_lsf_PulseEffectManager
#ifdef __cplusplus
extern "C" {
#endif
#undef org_allseen_lsf_PulseEffectManager_MAX_PULSE_EFFECTS
#define org_allseen_lsf_PulseEffectManager_MAX_PULSE_EFFECTS 100L
/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    getAllPulseEffectIDs
 * Signature: ()Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_getAllPulseEffectIDs
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    getPulseEffect
 * Signature: (Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_getPulseEffect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    applyPulseEffectOnLamps
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_applyPulseEffectOnLamps
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    applyPulseEffectOnLampGroups
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_applyPulseEffectOnLampGroups
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    getPulseEffectName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_getPulseEffectName
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    setPulseEffectName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_setPulseEffectName
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    createPulseEffect
 * Signature: (Lorg/allseen/lsf/sdk/TrackingID;Lorg/allseen/lsf/PulseEffect;Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_createPulseEffect
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    updatePulseEffect
 * Signature: (Ljava/lang/String;Lorg/allseen/lsf/PulseEffect;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_updatePulseEffect
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    deletePulseEffect
 * Signature: (Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_deletePulseEffect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    getPulseEffectDataSet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/allseen/lsf/sdk/ControllerClientStatus;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectManager_getPulseEffectDataSet
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    createNativeObject
 * Signature: (Lorg/allseen/lsf/ControllerClient;Lorg/allseen/lsf/PulseEffectManagerCallback;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectManager_createNativeObject
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectManager
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectManager_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
