/******************************************************************************
 * Copyright (c) AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_PulseEffectV2 */

#ifndef _Included_org_allseen_lsf_PulseEffectV2
#define _Included_org_allseen_lsf_PulseEffectV2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setToLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setToLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getToLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectV2_getToLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setFromLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setFromLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getFromLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectV2_getFromLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setToPresetID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setToPresetID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getToPresetID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PulseEffectV2_getToPresetID
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setFromPresetID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setFromPresetID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getFromPresetID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PulseEffectV2_getFromPresetID
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setPulsePeriod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setPulsePeriod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getPulsePeriod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffectV2_getPulsePeriod
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setPulseDuration
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setPulseDuration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getPulseDuration
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffectV2_getPulseDuration
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setNumPulses
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setNumPulses
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getNumPulses
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffectV2_getNumPulses
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
