/******************************************************************************
 * Copyright (c) 2014, AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_PresetPulseEffect */

#ifndef _Included_org_allseen_lsf_PresetPulseEffect
#define _Included_org_allseen_lsf_PresetPulseEffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    setLamps
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_setLamps
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    getLamps
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_PresetPulseEffect_getLamps
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    setLampGroups
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_setLampGroups
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    getLampGroups
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_allseen_lsf_PresetPulseEffect_getLampGroups
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    setPulsePeriod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_setPulsePeriod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    getPulsePeriod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PresetPulseEffect_getPulsePeriod
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    setPulseDuration
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_setPulseDuration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    getPulseDuration
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PresetPulseEffect_getPulseDuration
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    setPulseCount
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_setPulseCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    getPulseCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PresetPulseEffect_getPulseCount
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    setFromPreset
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_setFromPreset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    getFromPreset
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PresetPulseEffect_getFromPreset
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    setToPreset
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_setToPreset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    getToPreset
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PresetPulseEffect_getToPreset
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PresetPulseEffect_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PresetPulseEffect
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PresetPulseEffect_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
