/******************************************************************************
 * Copyright (c) 2014, AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_LampDetails */

#ifndef _Included_org_allseen_lsf_LampDetails
#define _Included_org_allseen_lsf_LampDetails
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getMake
 * Signature: ()Lorg/allseen/lsf/LampMake;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_LampDetails_getMake
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getModel
 * Signature: ()Lorg/allseen/lsf/LampModel;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_LampDetails_getModel
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getType
 * Signature: ()Lorg/allseen/lsf/DeviceType;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_LampDetails_getType
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getLampType
 * Signature: ()Lorg/allseen/lsf/LampType;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_LampDetails_getLampType
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getLampBaseType
 * Signature: ()Lorg/allseen/lsf/BaseType;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_LampDetails_getLampBaseType
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getLampBeamAngle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getLampBeamAngle
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    isDimmable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_allseen_lsf_LampDetails_isDimmable
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    hasColor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_allseen_lsf_LampDetails_hasColor
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    hasVariableColorTemp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_allseen_lsf_LampDetails_hasVariableColorTemp
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    hasEffects
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_allseen_lsf_LampDetails_hasEffects
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getMinVoltage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getMinVoltage
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getMaxVoltage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getMaxVoltage
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getWattage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getWattage
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getWattageEquivalent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getIncandescentEquivalent
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getMaxOutput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getMaxLumens
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getMinTemperature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getMinTemperature
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getMaxTemperature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getMaxTemperature
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getColorRenderingIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_allseen_lsf_LampDetails_getColorRenderingIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    getLampID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_LampDetails_getLampID
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_LampDetails_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_LampDetails
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_LampDetails_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
