# Copyright (c) 2013 - 2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.


Import('onb_env')

if not server_sample_env.has_key('_ALLJOYNCORE_'):
    server_sample_env.Append(LIBS = ['alljoyn'])
    if server_sample_env['BR'] == 'on' :
        brFile = server_sample_env.subst('$DISTDIR') + '/cpp/lib/BundledRouter.o'
        server_sample_env['brobj'] = File(brFile)
        server_sample_env['ajrlib'] = 'ajrouter'
    if server_sample_env['OS'] == 'openwrt':
        server_sample_env.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

# Make onboarding dist a sub-directory of the alljoyn dist.  This avoids any conflicts with alljoyn dist targets.
onb_env['ONBOARDING_DISTDIR'] = onb_env['DISTDIR'] + '/onboarding'

onb_env.Install('$ONBOARDING_DISTDIR/inc/alljoyn/onboarding', onb_env.Glob('inc/alljoyn/onboarding/*.h'))

# libraries
onb_env.Install('$ONBOARDING_DISTDIR/lib', onb_env.SConscript('src/SConscript', exports = ['onb_env']))

# Sample programs
if onb_env['BUILD_SERVICES_SAMPLES'] == 'on':
    onb_env.Install('$ONBOARDING_DISTDIR/bin', onb_env.SConscript('samples/SConscript', exports = ['onb_env']))

# onboarding-daemon
onb_env.Install('$ONBOARDING_DISTDIR/bin', onb_env.SConscript('src/OnboardingDaemon/SConscript', exports = ['onb_env']))

# Build docs
installDocs = services_common_env.SConscript('docs/SConscript', exports = ['services_common_env'])
services_common_env.Depends(installDocs, services_common_env.Glob('$SC_DISTDIR/inc/alljoyn/services_common/*.h'));
