# Copyright (c) 2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('gateway_env')

gateway_env['GWMA_DISTDIR'] = gateway_env['DISTDIR'] + '/gatewayMgmtApp'

gateway_env.Append(LIBPATH = '$GWMA_DISTDIR/lib');
gateway_env.Append(CPPPATH = '$GWMA_DISTDIR/inc');

gateway_env.Install('$GWMA_DISTDIR/inc/alljoyn/gateway', gateway_env.Glob('inc/alljoyn/gateway/*.h'))
gateway_env.Install('$GWMA_DISTDIR/bin', gateway_env.SConscript('src/SConscript', exports = ['gateway_env']))
gateway_env.Install('$GWMA_DISTDIR/bin', File('manifest.xsd'))
gateway_env.Install('$GWMA_DISTDIR/bin', File('installPackage.sh'))
gateway_env.Install('$GWMA_DISTDIR/bin', File('removePackage.sh'))
gateway_env.Install('$GWMA_DISTDIR/bin', File('gwagent-config.xml'))

# Build docs
installedDocs = gateway_env.SConscript('docs/SConscript', exports = ['gateway_env'])
gateway_env.Depends(installedDocs, gateway_env.Glob('$GWMA_DISTDIR/inc/alljoyn/gateway/*.h'));
