# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('about_env')
import os

# even though we have deprecated the About Service code we still want to build
# the code till the code is ready for removal.
if about_env['OS_GROUP'] == 'posix':
    about_env.Append(CXXFLAGS = ['-Wno-deprecated-declarations'])

# Sources
srcs = about_env.Glob('*.cc')

# Platform specific sources
if about_env['OS'] == 'android':
    srcs += about_env.Glob('$OS/*.cc')
else:
    srcs += about_env.Glob('$OS_GROUP/*.cc')

libs = []

# Static library
objs = about_env.Object(srcs)
libs.append(about_env.StaticLibrary('alljoyn_about', objs))

# Shared library
if about_env.get('LIBTYPE', 'static') != 'static':
    shobjs = about_env.SharedObject(srcs)
    libs.append(about_env.SharedLibrary('alljoyn_about', shobjs))

Return ('libs')
