#******************************************************************************
# Copyright (c) 2013-2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
#*****************************************************************************

Import('gateway_env')
import os

gateway_env.Append(CPPPATH = ['$LIBXML2_BASE'])
gateway_env.Append(LIBS = ['libxml2'])
gateway_env.Prepend(LIBS = ['alljoyn_about', 'alljoyn_services_common'])

srcs = gateway_env.Glob('*.cc')
srcs.extend(gateway_env.Glob('busObjects/*.cc'))    
srcs.extend(gateway_env.Glob('app/*.cc'))
objs = gateway_env.Object(srcs)

prog = gateway_env.Program('alljoyn-gwagent', objs)

Return('prog')
