# Contributed by Qualcomm Connected Experiences, Inc.,
# with authorization from the AllSeen Alliance, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Pursuant to Section 1 of the License, the work of authorship constituting
# a Work and any Contribution incorporated in the Work shall mean only that
# Contributor's code submissions authored by that Contributor.  Any rights
# granted under the License are conditioned upon acceptance of these
# clarifications.
import os
import subprocess
import sys
import time
Import('env')

# The return value is the collection of files installed in the build destination.
returnValue = []

# Add support for multiple build targets in the same workset
env.VariantDir('build', 'src', duplicate = 0)

#Generate the onboarding Lib using the onboarding SConscript
prog = env.Install('$DISTDIR/lib', env.SConscript('build/SConscript', exports='env'))

returnValue += prog

Return('returnValue')
