/******************************************************************************
 * Copyright AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 ******************************************************************************/

#ifdef LSF_BINDINGS
#include <lsf/controllerservice/ServiceDescription.h>
#else
#include <ServiceDescription.h>
#endif

#define QCC_MODULE "SERVICE_DESCRIPTION"

namespace lsf {

OPTIONAL_NAMESPACE_CONTROLLER_SERVICE

const std::string ControllerServiceDescription =
    "<node>"
    "  <interface name='org.allseen.LSF.ControllerService'>"
    "  <property name='Version' type='u' access='read'/>"
    "    <method name='LightingResetControllerService'>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "    </method>"
    "    <method name='GetControllerServiceVersion'>"
    "      <arg name='version' type='u' direction='out'/>"
    "    </method>"
    "    <signal name='ControllerServiceLightingReset'>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServiceLampDescription =
    "<node>"
    "  <interface name='org.allseen.LSF.ControllerService.Lamp'>"
    "    <property name='Version' type='u' access='read'/>"
    "    <method name='GetAllLampIDs'>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetLampSupportedLanguages'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='supportedLanguages' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetLampManufacturer'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='manufacturer' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetLampName'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='lampName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='SetLampName'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='lampName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetLampDetails'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampDetails' type='a{sv}' direction='out'/>"
    "    </method>"
    "    <method name='GetLampParameters'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampParameters' type='a{sv}' direction='out'/>"
    "    </method>"
    "    <method name='GetLampParametersField'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='lampParameterFieldName' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampParameterFieldName' type='s' direction='out'/>"
    "      <arg name='lampParameterFieldValue' type='v' direction='out'/>"
    "    </method>"
    "    <method name='GetLampState'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampState' type='a{sv}' direction='out'/>"
    "    </method>"
    "    <method name='GetLampStateField'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='lampStateFieldName' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampStateFieldName' type='s' direction='out'/>"
    "      <arg name='lampStateFieldValue' type='v' direction='out'/>"
    "    </method>"
    "    <method name='TransitionLampState'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='lampState' type='a{sv}' direction='in'/>"
    "      <arg name='transitionPeriod' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='PulseLampWithState'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='fromLampState' type='a{sv}' direction='in'/>"
    "      <arg name='toLampState' type='a{sv}' direction='in'/>"
    "      <arg name='period' type='u' direction='in'/>"
    "      <arg name='duration' type='u' direction='in'/>"
    "      <arg name='numPulses' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='PulseLampWithPreset'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='fromPresetID' type='s' direction='in'/>"
    "      <arg name='toPresetID' type='s' direction='in'/>"
    "      <arg name='period' type='u' direction='in'/>"
    "      <arg name='duration' type='u' direction='in'/>"
    "      <arg name='numPulses' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='TransitionLampStateToPreset'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='transitionPeriod' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='TransitionLampStateField'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='lampStateFieldName' type='s' direction='in'/>"
    "      <arg name='lampStateFieldValue' type='v' direction='in'/>"
    "      <arg name='transitionPeriod' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampStateFieldName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='ResetLampState'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='ResetLampStateField'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='lampStateFieldName' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampStateFieldName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetLampFaults'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampFaults' type='au' direction='out'/>"
    "    </method>"
    "    <method name='ClearLampFault'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='lampFault' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampFault' type='u' direction='out'/>"
    "    </method>"
    "    <method name='GetLampServiceVersion'>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampServiceVersion' type='u' direction='out'/>"
    "    </method>"
    "    <signal name='LampNameChanged'>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampName' type='s' direction='out'/>"
    "    </signal>"
    "    <signal name='LampStateChanged'>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='lampState' type='a{sv}' direction='out'/>"
    "    </signal>"
    "    <signal name='LampsFound'>"
    "      <arg name='lampIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='LampsLost'>"
    "      <arg name='lampIDs' type='as' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServiceLampGroupDescription =
    "<node>"
    "  <interface name='org.allseen.LSF.ControllerService.LampGroup'>"
    "  <property name='Version' type='u' access='read'/>"
    "    <method name='GetAllLampGroupIDs'>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetLampGroupName'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='lampGroupName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='SetLampGroupName'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='lampGroupName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "    </method>"
    "    <method name='CreateLampGroup'>"
    "      <arg name='lampIDs' type='as' direction='in'/>"
    "      <arg name='lampGroupIDs' type='as' direction='in'/>"
    "      <arg name='lampGroupName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='UpdateLampGroup'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='lampIDs' type='as' direction='in'/>"
    "      <arg name='lampGroupIDs' type='as' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='DeleteLampGroup'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetLampGroup'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "      <arg name='lampIDs' type='as' direction='out'/>"
    "      <arg name='lampGroupIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='TransitionLampGroupState'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='lampState' type='a{sv}' direction='in'/>"
    "      <arg name='transitionPeriod' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='PulseLampGroupWithState'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='fromLampGroupState' type='a{sv}' direction='in'/>"
    "      <arg name='toLampGroupState' type='a{sv}' direction='in'/>"
    "      <arg name='period' type='u' direction='in'/>"
    "      <arg name='duration' type='u' direction='in'/>"
    "      <arg name='numPulses' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='PulseLampGroupWithPreset'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='fromPresetID' type='s' direction='in'/>"
    "      <arg name='toPresetID' type='s' direction='in'/>"
    "      <arg name='period' type='u' direction='in'/>"
    "      <arg name='duration' type='u' direction='in'/>"
    "      <arg name='numPulses' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='TransitionLampGroupStateToPreset'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='transitionPeriod' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='TransitionLampGroupStateField'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='lampGroupStateFieldName' type='s' direction='in'/>"
    "      <arg name='lampGroupStateFieldValue' type='v' direction='in'/>"
    "      <arg name='transitionPeriod' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "      <arg name='lampGroupStateFieldName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='ResetLampGroupState'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='ResetLampGroupStateField'>"
    "      <arg name='lampGroupID' type='s' direction='in'/>"
    "      <arg name='lampGroupStateFieldName' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampGroupID' type='s' direction='out'/>"
    "      <arg name='lampGroupStateFieldName' type='s' direction='out'/>"
    "    </method>"
    "    <signal name='LampGroupsNameChanged'>"
    "      <arg name='lampGroupsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='LampGroupsCreated'>"
    "      <arg name='lampGroupsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='LampGroupsUpdated'>"
    "      <arg name='lampGroupsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='LampGroupsDeleted'>"
    "      <arg name='lampGroupsIDs' type='as' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServicePresetDescription =
    "<node>"
    "  <interface name='org.allseen.LSF.ControllerService.Preset'>"
    "  <property name='Version' type='u' access='read'/>"
    "    <method name='GetDefaultLampState'>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampState' type='a{sv}' direction='out'/>"
    "    </method>"
    "    <method name='SetDefaultLampState'>"
    "      <arg name='lampState' type='a{sv}' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "    </method>"
    "    <method name='GetAllPresetIDs'>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='presetIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetPresetName'>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='presetID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='presetName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='SetPresetName'>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='presetName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='presetID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "    </method>"
    "    <method name='CreatePreset'>"
    "      <arg name='lampState' type='a{sv}' direction='in'/>"
    "      <arg name='presetName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='presetID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='UpdatePreset'>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='lampState' type='a{sv}' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='presetID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='DeletePreset'>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='presetID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetPreset'>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='presetID' type='s' direction='out'/>"
    "      <arg name='lampState' type='a{sv}' direction='out'/>"
    "    </method>"
    "    <signal name='DefaultLampStateChanged'>"
    "    </signal>"
    "    <signal name='PresetsNameChanged'>"
    "      <arg name='presetIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='PresetsCreated'>"
    "      <arg name='presetsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='PresetsUpdated'>"
    "      <arg name='presetsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='PresetsDeleted'>"
    "      <arg name='presetsIDs' type='as' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServiceTransitionEffectDescription =
    "<node xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.allseenalliance.org/schemas/introspect.xsd\">"
    "  <interface name='org.allseen.LSF.ControllerService.TransitionEffect'>"
    "    <description language=\"en\">This interface is provided by the LSF Controller Service to enable the LSF Controller Clients to create, update, delete, lookup and apply Transition Effects on Lamps.</description>"
    "     <annotation name=\"org.alljoyn.Bus.Secure\" value=\"off\"/>"
    "    <property name='Version' type='u' access='read'>"
    "        <description language=\"en\">Interface version</description>"
    "        <annotation name=\"org.freedesktop.DBus.Property.EmitsChangedSignal\" value=\"true\"/>"
    "    </property>"
    "    <method name='GetAllTransitionEffectIDs'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch all the Transition Effect IDs.</description>"
    "       <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetTransitionEffectName'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch the name of a Transition Effect specified by the transitionEffectID.</description>"
    "	   <arg name='transitionEffectID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='transitionEffectName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='SetTransitionEffectName'>"
    "      <description language=\"en\">	This method allows the LSF Controller Clients to set the name of a Transition Effect specified by the transitionEffectID.</description>"
    "       <arg name='transitionEffectID' type='s' direction='in'/>"
    "      <arg name='transitionEffectName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "    </method>"
    "    <method name='CreateTransitionEffect'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to create a Transition Effect.</description>"
    "       <arg name='lampState' type='a{sv}' direction='in'/>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='transitionPeriod' type='u' direction='in'/>"
    "      <arg name='transitionEffectName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='UpdateTransitionEffect'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to update a Transition Effect.</description>"
    "       <arg name='transitionEffectID' type='s' direction='in'/>"
    "      <arg name='lampState' type='a{sv}' direction='in'/>"
    "      <arg name='presetID' type='s' direction='in'/>"
    "      <arg name='transitionPeriod' type='u' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='DeleteTransitionEffect'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to delete a Transition Effect.</description>"
    "       <arg name='transitionEffectID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetTransitionEffect'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch a Transition Effect.</description>"
    "       <arg name='transitionEffectID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectID' type='s' direction='out'/>"
    "      <arg name='lampState' type='a{sv}' direction='out'/>"
    "      <arg name='presetID' type='s' direction='out'/>"
    "      <arg name='transitionPeriod' type='u' direction='out'/>"
    "    </method>"
    "    <method name='ApplyTransitionEffectOnLamps'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to apply a Transition Effect on a set of Lamps.</description>"
    "       <arg name='transitionEffectID' type='s' direction='in'/>"
    "      <arg name='lampIDs' type='as' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectID' type='s' direction='out'/>"
    "      <arg name='lampIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='ApplyTransitionEffectOnLampGroups'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to apply a Transition Effect on a set of LampGroups.</description>"
    "       <arg name='transitionEffectID' type='s' direction='in'/>"
    "      <arg name='lampGroupIDs' type='as' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='transitionEffectID' type='s' direction='out'/>"
    "      <arg name='lampGroupIDs' type='as' direction='out'/>"
    "    </method>"
    "    <signal name='TransitionEffectsNameChanged' sessioncast=\"true\">"
    "      <description language=\"en\">The TransitionEffectsNameChanged signal is used to notify the list of the Transition Effect IDs whose names have changed.</description>"
    "      <arg name='transitionEffectIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='TransitionEffectsCreated' sessioncast=\"true\">"
    "      <description language=\"en\">The TransitionEffectsCreated signal is used to notify the list of the Transition Effect IDs that have been created.</description>"
    "      <arg name='transitionEffectsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='TransitionEffectsUpdated' sessioncast=\"true\">"
    "      <description language=\"en\">The TransitionEffectsUpdated signal is used to notify the list of the Transition Effect IDs that have been updated.</description>"
    "      <arg name='transitionEffectsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='TransitionEffectsDeleted' sessioncast=\"true\">"
    "      <description language=\"en\">The TransitionEffectsDeleted signal is used to notify the list of the Transition Effect IDs that have been deleted.</description>"
    "      <arg name='transitionEffectsIDs' type='as' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServicePulseEffectDescription =
    "<node xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.allseenalliance.org/schemas/introspect.xsd\">"
    "  <interface name='org.allseen.LSF.ControllerService.PulseEffect'>"
    "    <description language=\"en\">This interface is provided by the LSF Controller Service to enable the LSF Controller Clients to create, update, delete, lookup and apply Pulse Effects on Lamps.</description>"
    "    <annotation name=\"org.alljoyn.Bus.Secure\" value=\"off\"/>"
    "    <property name='Version' type='u' access='read'>"
    "        <description language=\"en\">Interface version</description>"
    "        <annotation name=\"org.freedesktop.DBus.Property.EmitsChangedSignal\" value=\"true\"/>"
    "    </property>"
    "    <method name='GetAllPulseEffectIDs'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch all the Pulse Effect IDs.</description>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "     <arg name='pulseEffectIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetPulseEffectName'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch the name of a Pulse Effect specified by the pulseEffectID.</description>"
    "      <arg name='pulseEffectID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='pulseEffectID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='pulseEffectName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='SetPulseEffectName'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to set the name of a Pulse Effect specified by the pulseEffectID. </description>"
    "      <arg name='pulseEffectID' type='s' direction='in'/>"
    "      <arg name='pulseEffectName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='pulseEffectID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "    </method>"
    "    <method name='CreatePulseEffect'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to create a Pulse Effect.</description>"
    "      <arg name='toLampState' type='a{sv}' direction='in'/>"
    "      <arg name='pulsePeriod' type='u' direction='in'/>"
    "      <arg name='pulseDuration' type='u' direction='in'/>"
    "      <arg name='numPulses' type='u' direction='in'/>"
    "      <arg name='fromLampState' type='a{sv}' direction='in'/>"
    "      <arg name='toPresetID' type='s' direction='in'/>"
    "      <arg name='fromPresetID' type='s' direction='in'/>"
    "      <arg name='pulseEffectName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='pulseEffectID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='UpdatePulseEffect'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to update a Pulse Effect.</description>"
    "      <arg name='pulseEffectID' type='s' direction='in'/>"
    "      <arg name='toLampState' type='a{sv}' direction='in'/>"
    "      <arg name='pulsePeriod' type='u' direction='in'/>"
    "      <arg name='pulseDuration' type='u' direction='in'/>"
    "      <arg name='numPulses' type='u' direction='in'/>"
    "      <arg name='fromLampState' type='a{sv}' direction='in'/>"
    "      <arg name='toPresetID' type='s' direction='in'/>"
    "      <arg name='fromPresetID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='pulseEffectID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='DeletePulseEffect'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to delete a Pulse Effect.</description>"
    "      <arg name='pulseEffectID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='pulseEffectID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetPulseEffect'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch a Pulse Effect.</description>"
    "      <arg name='pulseEffectID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='pulseEffectID' type='s' direction='out'/>"
    "      <arg name='toLampState' type='a{sv}' direction='out'/>"
    "      <arg name='pulsePeriod' type='u' direction='out'/>"
    "      <arg name='pulseDuration' type='u' direction='out'/>"
    "      <arg name='numPulses' type='u' direction='out'/>"
    "      <arg name='fromLampState' type='a{sv}' direction='out'/>"
    "      <arg name='toPresetID' type='s' direction='out'/>"
    "      <arg name='fromPresetID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='ApplyPulseEffectOnLamps'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to apply a Pulse Effect on a set of Lamps.</description>"
    "      <arg name='pulseEffectID' type='s' direction='in'/>"
    "      <arg name='lampIDs' type='as' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='pulseEffectID' type='s' direction='out'/>"
    "      <arg name='lampIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='ApplyPulseEffectOnLampGroups'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to apply a Pulse Effect on a set of LampGroups.</description>"
    "      <arg name='pulseEffectID' type='s' direction='in'/>"
    "      <arg name='lampGroupIDs' type='as' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='pulseEffectID' type='s' direction='out'/>"
    "      <arg name='lampGroupIDs' type='as' direction='out'/>"
    "   </method>"
    "    <signal name='PulseEffectsNameChanged'>"
    "     <description language=\"en\">The PulseEffectsNameChanged signal is used to notify the list of the Pulse Effect IDs whose names have changed.</description>"
    "      <arg name='pulseEffectIDs' type='as' direction='out'/>"
    "    </signal>"
    "   <signal name='PulseEffectsCreated'>"
    "      <description language=\"en\">The PulseEffectsCreated signal is used to notify the list of the Pulse Effect IDs that have been created.</description>"
    "      <arg name='pulseEffectsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='PulseEffectsUpdated'>"
    "      <description language=\"en\">The PulseEffectsUpdated signal is used to notify the list of the Pulse Effect IDs that have been updated.</description>"
    "      <arg name='pulseEffectsIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='PulseEffectsDeleted'>"
    "      <description language=\"en\">The PulseEffectsDeleted signal is used to notify the list of the Pulse Effect IDs that have been deleted.</description>"
    "      <arg name='pulseEffectsIDs' type='as' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServiceSceneDescription =
    "<node>"
    "  <interface name='org.allseen.LSF.ControllerService.Scene'>"
    "  <property name='Version' type='u' access='read'/>"
    "    <method name='GetAllSceneIDs'>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetSceneName'>"
    "      <arg name='sceneID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='sceneName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='SetSceneName'>"
    "      <arg name='sceneID' type='s' direction='in'/>"
    "      <arg name='sceneName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "    </method>"
    "    <method name='CreateScene'>"
    "      <arg name='transitionlampsLampGroupsToState' type='a(asasa{sv}u)' direction='in'/>"
    "      <arg name='transitionlampsLampGroupsToPreset' type='a(asassu)' direction='in'/>"
    "      <arg name='pulselampsLampGroupsWithState' type='a(asasa{sv}a{sv}uuu)' direction='in'/>"
    "      <arg name='pulselampsLampGroupsWithPreset' type='a(asasssuuu)' direction='in'/>"
    "      <arg name='sceneName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='UpdateScene'>"
    "      <arg name='sceneID' type='s' direction='in'/>"
    "      <arg name='transitionlampsLampGroupsToState' type='a(asasa{sv}u)' direction='in'/>"
    "      <arg name='transitionlampsLampGroupsToPreset' type='a(asassu)' direction='in'/>"
    "      <arg name='pulselampsLampGroupsWithState' type='a(asasa{sv}a{sv}uuu)' direction='in'/>"
    "      <arg name='pulselampsLampGroupsWithPreset' type='a(asasssuuu)' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='DeleteScene'>"
    "      <arg name='sceneID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetScene'>"
    "      <arg name='sceneID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "      <arg name='transitionlampsLampGroupsToState' type='a(asasa{sv}u)' direction='out'/>"
    "      <arg name='transitionlampsLampGroupsToPreset' type='a(asassu)' direction='out'/>"
    "      <arg name='pulselampsLampGroupsWithState' type='a(asasa{sv}a{sv}uuu)' direction='out'/>"
    "      <arg name='pulselampsLampGroupsWithPreset' type='a(asasssuuu)' direction='out'/>"
    "    </method>"
    "    <method name='ApplyScene'>"
    "      <arg name='sceneID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "    </method>"
    "    <signal name='ScenesNameChanged'>"
    "      <arg name='sceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='ScenesCreated'>"
    "      <arg name='sceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='ScenesUpdated'>"
    "      <arg name='sceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='ScenesDeleted'>"
    "      <arg name='sceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='ScenesApplied'>"
    "      <arg name='sceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServiceSceneWithSceneElementsDescription =
    "<node xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.allseenalliance.org/schemas/introspect.xsd\">"
    "  <interface name='org.allseen.LSF.ControllerService.SceneWithSceneElements'>"
    "    <description language=\"en\">This interface is provided by the LSF Controller Service to enable the LSF Controller Clients to create, update and lookup Scene with Scene with Scene Elements.</description>"
    "    <annotation name=\"org.alljoyn.Bus.Secure\" value=\"off\"/>"
    "    <property name='Version' type='u' access='read'>"
    "        <description language=\"en\">Interface version</description>"
    "        <annotation name=\"org.freedesktop.DBus.Property.EmitsChangedSignal\" value=\"true\"/>"
    "    </property>"
    "    <method name='CreateSceneWithSceneElements'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients  to create a Scene with Scene Elements.</description>"
    "      <arg name='sceneElementIDs' type='as' direction='in'/>"
    "      <arg name='sceneName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='UpdateSceneWithSceneElements'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to update a Scene with Scene Elements.</description>"
    "      <arg name='sceneID' type='s' direction='in'/>"
    "      <arg name='sceneElementIDs' type='as' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetSceneWithSceneElements'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch a Scene with Scene Elements.</description>"
    "      <arg name='sceneID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneID' type='s' direction='out'/>"
    "      <arg name='sceneElementIDs' type='as' direction='out'/>"
    "    </method>"
    "  </interface>"
    "</node>";

const std::string ControllerServiceSceneElementDescription =
    "<node xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.allseenalliance.org/schemas/introspect.xsd\">"
    "  <interface name='org.allseen.LSF.ControllerService.SceneElement'>"
    "    <description language=\"en\">This interface is provided by the LSF Controller Service to enable the LSF Controller Clients to create, update, delete, lookup and apply Scene Elements on Lamps.</description>"
    "    <annotation name=\"org.alljoyn.Bus.Secure\" value=\"off\"/>"
    "    <property name='Version' type='u' access='read'>"
    "        <description language=\"en\">Interface version</description>"
    "        <annotation name=\"org.freedesktop.DBus.Property.EmitsChangedSignal\" value=\"true\"/>"
    "    </property>"
    "    <method name='GetAllSceneElementIDs'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch all the Scene Element IDs.</description>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneElementIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetSceneElementName'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch the name of a Scene Element specified by the sceneElementID.</description>"
    "      <arg name='sceneElementID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneElementID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='sceneElementName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='SetSceneElementName'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to set the name of a Scene Element specified by the sceneElementID.</description>"
    "      <arg name='sceneElementID' type='s' direction='in'/>"
    "      <arg name='sceneElementName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneElementID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "    </method>"
    "    <method name='CreateSceneElement'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to create a Scene Element.</description>"
    "      <arg name='SceneElement' type='asass' direction='in'/>"
    "      <arg name='sceneElementName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneElementID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='UpdateSceneElement'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to update a Scene Element.</description>"
    "      <arg name='sceneElementID' type='s' direction='in'/>"
    "      <arg name='SceneElement' type='asass' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneElementID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='DeleteSceneElement'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to delete a Scene Element.</description>"
    "      <arg name='sceneElementID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneElementID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetSceneElement'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch a Scene Element.</description>"
    "      <arg name='sceneElementID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneElementID' type='s' direction='out'/>"
    "      <arg name='SceneElement' type='asass' direction='out'/>"
    "    </method>"
    "    <method name='ApplySceneElement'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to apply a Scene Element.</description>"
    "      <arg name='sceneElementID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='sceneElementID' type='s' direction='out'/>"
    "    </method>"
    "    <signal name='SceneElementsNameChanged' sessioncast=\"true\">"
    "      <description language=\"en\">The SceneElementsNameChanged signal is used to notify the list of the Scene Element IDs whose names have changed.</description>"
    "      <arg name='sceneElementIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='SceneElementsCreated' sessioncast=\"true\">"
    "      <description language=\"en\">The SceneElementsCreated signal is used to notify the list of the Scene Element IDs that have been created.</description>"
    "      <arg name='sceneElementIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='SceneElementsUpdated' sessioncast=\"true\">"
    "      <description language=\"en\">The SceneElementsCreated signal is used to notify the list of the Scene Element IDs that have been updated.</description>"
    "      <arg name='sceneElementIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='SceneElementsDeleted' sessioncast=\"true\">"
    "      <description language=\"en\">The SceneElementsDeleted signal is used to notify the list of the Scene Element IDs that have been deleted.</description>"
    "      <arg name='sceneElementIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='SceneElementsApplied' sessioncast=\"true\">"
    "      <description language=\"en\">The SceneElementsApplied signal is used to notify the list of the Scene Element IDs that have been applied.</description>"
    "      <arg name='sceneElementIDs' type='as' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServiceMasterSceneDescription =
    "<node>"
    "  <interface name='org.allseen.LSF.ControllerService.MasterScene'>"
    "  <property name='Version' type='u' access='read'/>"
    "    <method name='GetAllMasterSceneIDs'>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='masterSceneIDs' type='as' direction='out'/>"
    "    </method>"
    "    <method name='GetMasterSceneName'>"
    "      <arg name='masterSceneID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='masterSceneID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='masterSceneName' type='s' direction='out'/>"
    "    </method>"
    "    <method name='SetMasterSceneName'>"
    "      <arg name='masterSceneID' type='s' direction='in'/>"
    "      <arg name='masterSceneName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='masterSceneID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "    </method>"
    "    <method name='CreateMasterScene'>"
    "      <arg name='scenes' type='as' direction='in'/>"
    "      <arg name='masterSceneName' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='masterSceneID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='UpdateMasterScene'>"
    "      <arg name='masterSceneID' type='s' direction='in'/>"
    "      <arg name='scenes' type='as' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='masterSceneID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='DeleteMasterScene'>"
    "      <arg name='masterSceneID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='masterSceneID' type='s' direction='out'/>"
    "    </method>"
    "    <method name='GetMasterScene'>"
    "      <arg name='masterSceneID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='masterSceneID' type='s' direction='out'/>"
    "      <arg name='scenes' type='as' direction='out'/>"
    "    </method>"
    "    <method name='ApplyMasterScene'>"
    "      <arg name='masterSceneID' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='masterSceneID' type='s' direction='out'/>"
    "    </method>"
    "    <signal name='MasterScenesNameChanged'>"
    "      <arg name='masterSceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='MasterScenesCreated'>"
    "      <arg name='masterSceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='MasterScenesUpdated'>"
    "      <arg name='masterSceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='MasterScenesDeleted'>"
    "      <arg name='masterSceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "    <signal name='MasterScenesApplied'>"
    "      <arg name='masterSceneIDs' type='as' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string LeaderElectionAndStateSyncDescription =
    "<node>"
    "  <interface name='org.allseen.LeaderElectionAndStateSync'>"
    "    <property name='Version' type='u' access='read'/>"
    "    <method name='GetChecksumAndModificationTimestamp'>"
    "      <arg name='checksumAndTimestamp' type='a(uut)' direction='out'/>"
    "    </method>"
    "    <method name='GetBlob'>"
    "      <arg name='blobType' type='u' direction='in'/>"
    "      <arg name='blobType' type='u' direction='out'/>"
    "      <arg name='blob' type='s' direction='out'/>"
    "      <arg name='checksum' type='u' direction='out'/>"
    "      <arg name='timestamp' type='t' direction='out'/>"
    "    </method>"
    "    <method name='Overthrow'>"
    "      <arg name='success' type='b' direction='out'/>"
    "    </method>"
    "    <signal name='BlobChanged'>"
    "      <arg name='blobType' type='u' direction='out'/>"
    "      <arg name='blob' type='s' direction='out'/>"
    "      <arg name='checksum' type='u' direction='out'/>"
    "      <arg name='timestamp' type='t' direction='out'/>"
    "    </signal>"
    "  </interface>"
    "</node>";

const std::string ControllerServiceDataSetDescription =
    "<node xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.allseenalliance.org/schemas/introspect.xsd\">"
    "  <interface name='org.allseen.LSF.ControllerService.DataSet'>"
    "    <description language=\"en\">This interface is provided by the LSF Controller Service to enable the LSF Controller Clients to fetch all the Lamp metadata using a single method call.</description>"
    "    <annotation name=\"org.alljoyn.Bus.Secure\" value=\"off\"/>"
    "    <property name='Version' type='u' access='read'>"
    "        <description language=\"en\">Interface version</description>"
    "        <annotation name=\"org.freedesktop.DBus.Property.EmitsChangedSignal\" value=\"true\"/>"
    "    </property>"
    "    <method name='GetLampDataSet'>"
    "      <description language=\"en\">This method allows the LSF Controller Clients to fetch all the Lamp metadata.</description>"
    "      <arg name='lampID' type='s' direction='in'/>"
    "      <arg name='language' type='s' direction='in'/>"
    "      <arg name='responseCode' type='u' direction='out'/>"
    "      <arg name='lampID' type='s' direction='out'/>"
    "      <arg name='language' type='s' direction='out'/>"
    "      <arg name='lampName' type='s' direction='out'/>"
    "      <arg name='lampDetails' type='a{sv}' direction='out'/>"
    "      <arg name='lampState' type='a{sv}' direction='out'/>"
    "      <arg name='lampParameters' type='a{sv}' direction='out'/>"
    "    </method>"
    "  </interface>"
    "</node>";

OPTIONAL_NAMESPACE_CLOSE

}
