# Copyright (c) 2013-2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

import os

Import('about_env')

about_env.Append(CPPPATH = [
                            Dir('inc'),
                            Dir('../../../services/services_common/tcl/inc'),
                            Dir('../../../services/sample_apps/tcl/ServerSample/inc'),
                           ])
Export('about_env')

variant_dir = 'obj'
if about_env.has_key('SERSAMP_VARIANT_DIR'):
    # avoid scons "two environments different actions" error
    # by defining separate variant dir for each env/app
    variant_dir += '/' + about_env['SERSAMP_VARIANT_DIR']

objs = SConscript('src/SConscript', variant_dir = variant_dir, duplicate = 0)

Return('objs')
