# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
#
import os
import difflib

Import('env')

jsdocenv = env.Clone()

vars = Variables()
vars.Add(PathVariable('JSDOC_DIR', 'The path to the JsDoc toolkit', os.environ.get('JSDOC_DIR'), PathVariable.PathIsDir))
vars.Update(jsdocenv)
Help(vars.GenerateHelpText(jsdocenv))

if jsdocenv.has_key('JSDOC_DIR'):
    jsdocenv.PrependENVPath('PATH', jsdocenv.get('JSDOC_DIR'))

# Build docs
if jsdocenv.has_key('JSDOC_DIR'):
    jsdocenv['JSDOC_TEMPLATE'] = jsdocenv.Dir('$JSDOC_DIR/templates/default')
    doc_out = jsdocenv.jsdoc3(target=[jsdocenv.Dir('html')], source=['alljoyn_doc'])
    documentation = jsdocenv.Install('$JS_DISTDIR/docs', 'html')
