# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.


Import('server_sample_env')

if not server_sample_env.has_key('_ALLJOYNCORE_'):
    server_sample_env.Append(LIBS = ['alljoyn'])
    if server_sample_env['BR'] == 'on' :
        server_sample_env['ajrlib'] = 'ajrouter'
    if server_sample_env['OS'] == 'openwrt':
        server_sample_env.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

# Make serversample dist a sub-directory of the alljoyn dist.  This avoids any conflicts with alljoyn dist targets.
server_sample_env['SAMPLE_APPS_DISTDIR'] = server_sample_env['DISTDIR'] + '/sample_apps'

# Sample programs
if server_sample_env['BUILD_SERVICES_SAMPLES'] == 'on':
    server_sample_env.Install('$SAMPLE_APPS_DISTDIR/bin', server_sample_env.SConscript('samples/SConscript', exports = ['server_sample_env']))

# Build docs
installDocs = server_sample_env.SConscript('docs/SConscript', exports = ['server_sample_env'])
server_sample_env.Depends(installDocs, server_sample_env.Glob('$ONBOARDING_DISTDIR/inc/alljoyn/onboarding/*.h'));
