# Copyright (c) 2013 - 2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('config_env')

if not config_env.has_key('_ALLJOYNCORE_'):
    config_env.Append(LIBS = ['alljoyn'])
    if config_env['BR'] == 'on' :
        brFile = config_env.subst('$DISTDIR') + '/cpp/lib/BundledRouter.o'
        config_env['brobj'] = File(brFile)
        config_env['ajrlib'] = 'ajrouter'
    if config_env['OS'] == 'openwrt':
        config_env.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

# Make config dist a sub-directory of the alljoyn dist.  This avoids any conflicts with alljoyn dist targets.
config_env['CONFIG_DISTDIR'] = config_env['DISTDIR'] + '/config'

config_env.Install('$CONFIG_DISTDIR/inc/alljoyn/config', config_env.Glob('inc/alljoyn/config/*.h'))

# Libraries
config_env.Install('$CONFIG_DISTDIR/lib', config_env.SConscript('src/SConscript', exports = ['config_env']))

# Sample programs
if config_env['BUILD_SERVICES_SAMPLES'] == 'on':
    config_env.Install('$CONFIG_DISTDIR/bin', config_env.SConscript('samples/SConscript', exports = ['config_env']))

# Build docs
installDocs = config_env.SConscript('docs/SConscript', exports = ['config_env'])
config_env.Depends(installDocs, config_env.Glob('$CONFIG_DISTDIR/inc/alljoyn/config/*.h'));
