# Copyright (c) 2013, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('services_common_env')
 
if not services_common_env.has_key('_ALLJOYNCORE_'):
    services_common_env.Append(LIBS = ['alljoyn'])
    if services_common_env['OS'] == 'openwrt':
        services_common_env.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

services_common_env['SC_DISTDIR'] = services_common_env['DISTDIR'] + '/services_common'

services_common_env.Install('$SC_DISTDIR/inc/alljoyn/services_common', services_common_env.Glob('inc/alljoyn/services_common/*.h'))
services_common_env.Install('$SC_DISTDIR/lib', services_common_env.SConscript('src/SConscript', exports = ['services_common_env']))

# Build docs
installDocs = services_common_env.SConscript('docs/SConscript', exports = ['services_common_env'])
services_common_env.Depends(installDocs, services_common_env.Glob('$SC_DISTDIR/inc/alljoyn/services_common/*.h'));
