/******************************************************************************
 * Copyright AllSeen Alliance. All rights reserved.
 *
 *    Contributed by Qualcomm Connected Experiences, Inc.,
 *    with authorization from the AllSeen Alliance, Inc.
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Pursuant to Section 1 of the License, the work of authorship constituting
 *    a Work and any Contribution incorporated in the Work shall mean only that
 *    Contributor's code submissions authored by that Contributor.  Any rights
 *    granted under the License are conditioned upon acceptance of these
 *    clarifications.
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_sample_event_tester_BusHandler */

#ifndef _Included_org_allseen_sample_event_tester_BusHandler
#define _Included_org_allseen_sample_event_tester_BusHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_sample_event_tester_BusHandler
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_sample_event_tester_BusHandler_initialize
    (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_org_allseen_sample_event_tester_BusHandler_startRuleEngine
    (JNIEnv *, jobject);

/*
 * Class:     org_allseen_sample_event_tester_BusHandler
 * Method:    dointrospection
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/langString;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_sample_event_tester_BusHandler_doIntrospection
    (JNIEnv *, jobject, jstring, jstring, jint);

JNIEXPORT void JNICALL Java_org_allseen_sample_event_tester_BusHandler_introspectionDone
    (JNIEnv *, jobject, jint);

JNIEXPORT jboolean JNICALL Java_org_allseen_sample_event_tester_BusHandler_enableEvent
    (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_org_allseen_sample_event_tester_BusHandler_callAction
    (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_allseen_sample_event_tester_BusHandler
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_sample_event_tester_BusHandler_shutdown
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
