# Contributed by Qualcomm Connected Experiences, Inc.,
# with authorization from the AllSeen Alliance, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Pursuant to Section 1 of the License, the work of authorship constituting
# a Work and any Contribution incorporated in the Work shall mean only that
# Contributor's code submissions authored by that Contributor.  Any rights
# granted under the License are conditioned upon acceptance of these
# clarifications.
import os
Import('env')

# Sample programs
progs = [
    env.Program('helloworld', 'helloworld.cc'),
    env.Program('hello_joystick_notif_send', 'solutions/hello_joystick_notif_send.cc'), 
    env.Program('hello_notif_rx_to_display', 'solutions/hello_notif_rx_to_display.cc'),
    env.Program('hello_print_string', 'solutions/hello_print_string.cc'),
    env.Program('hello_service_print_string', 'solutions/hello_service_add_printstring_method.cc'),
    env.Program('hello_client_print_string', 'solutions/hello_client_call_printstring_method.cc'),
    env.Program('hello_client_multi_print_string', 'solutions/hello_client_multi_call_printstring_method.cc'),
    env.Program('hello_service_multi_print_string', 'solutions/hello_service_multi_add_printstring_method.cc')
]

returnValue = env.Install('$DISTDIR/bin', progs)
Return ('returnValue')
