# Contributed by Qualcomm Connected Experiences, Inc.,
# with authorization from the AllSeen Alliance, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Pursuant to Section 1 of the License, the work of authorship constituting
# a Work and any Contribution incorporated in the Work shall mean only that
# Contributor's code submissions authored by that Contributor.  Any rights
# granted under the License are conditioned upon acceptance of these
# clarifications.
import os

Import('env')

samples_env = env.Clone()

progs = []

samples_env.Append(CPPDEFINES = {
    'AJ_MAIN': None,
    'AJ_NUM_REPLY_CONTEXTS': '8',
    'AJ_MAX_OBJECT_LISTS': '9',
    'ANNOUNCE_BASED_DISCOVERY': '1'
})
samples_env.Append(CPPPATH = './inc')

samples_env.Append(LIBPATH = '#dist/lib')
samples_env.Prepend(LIBS = ['ajtcl_services_config'])
samples_env.Prepend(LIBS = ['ajtcl_services'])

common_objs = samples_env.Object(samples_env.Glob('common/*.c'))

build_samples = [
#    'Controllee',
#    'NotificationConsumer',
#    'NotificationProducer',
    'NotifConfig'
]

#if env['enable_onboarding']:
#    build_samples.append('Onboardee')

#if env['TIME_SERVICE']:
#    build_samples.append('TimeServer')

for sample in build_samples:
    objs = samples_env.Object(samples_env.Glob(sample + '/*.c'))
#    if sample == 'TimeClient':
#        progs.append(samples_env.Program(sample + 'Sample', objs))
#    else:
    progs.append(samples_env.Program(sample + 'Sample', common_objs + objs))

samples_env.Install('#dist/bin', progs)
