# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
#

Import('env')

test_env = env.Clone()

if test_env['BR'] == 'on':
    #Build apps with bundled daemon support
    test_env.Prepend(LIBS = [test_env['ajrlib']])

test_env.Prepend(LIBS = [test_env['ALLJOYN_C_LIB_STATIC']])

test_programs = ['bbcclient', 'bbcservice']
built_test_programs = []
for test_p in test_programs:
    test_obj = test_env.Object(test_p)
    built_test_programs.append(test_env.Program(test_p,  [test_obj]))

if test_env['OS_GROUP'] != 'windows':
    test_env.Install('$C_DISTDIR/bin', built_test_programs)
