# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
#

Import('env')

snippets_env = env.Clone()

if snippets_env['BR'] == 'on':
    # Build apps with bundled daemon support
    snippets_env.Prepend(LIBS = [snippets_env['ajrlib']])

# only include command line samples, unit test, test programs if we are not
# building for iOS. No support on iOS for command line applications.
if not (snippets_env['OS'] == 'darwin' and snippets_env['CPU'] in ['arm', 'armv7', 'armv7s', 'arm64',]):
    snippets_env.Program('usingmsgarg',  ['usingmsgarg.cpp'])
    snippets_env.Program('create_interface_from_xml_interface', ['create_interface_from_xml_interface.cpp'])
    snippets_env.Program('create_interface_from_xml_node', ['create_interface_from_xml_node.cpp'])
    snippets_env.Program('create_interface_using_code', ['create_interface_using_code.cpp'])
