# Contributed by Qualcomm Connected Experiences, Inc.,
# with authorization from the AllSeen Alliance, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Pursuant to Section 1 of the License, the work of authorship constituting
# a Work and any Contribution incorporated in the Work shall mean only that
# Contributor's code submissions authored by that Contributor.  Any rights
# granted under the License are conditioned upon acceptance of these
# clarifications.
import os

Import('env')

test_env = env.Clone()

progs = []

test_env.Append(CPPDEFINES = 'AJ_MAIN')
test_env.Append(CPPPATH = './inc')

test_env.Append(LIBPATH = '#dist/lib')
test_env.Prepend(LIBS = 'ajtcl_services')

common_srcs = [ s for s in Glob('common/*.c')
                if test_env['enable_onboarding'] or not s.name == 'OnboardingSample.c' ]

common_objs = test_env.Object(common_srcs)

build_tests = [
    'ACServer',
    'AllInOneServer'
]

for test in build_tests:
    objs = test_env.Object(Glob(test + '/*.c'))
    progs.append(test_env.Program(test + 'Test', common_objs + objs))

test_env.Install('#dist/bin', progs)
