# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

import os
Import('services_common_env')

returnValue = []

docservices_common_env = services_common_env.Clone()

# Build docs
if docservices_common_env['DOCS'] == 'html':
    # the target directory 'docs/tmp' is never built this will cause doxygen 
    # to run every time DOCS == 'html'
    generateDocs = docservices_common_env.Doxygen(source='Doxygen_html', target=[Dir('tmp'), Dir('html')])
    returnValue = docservices_common_env.Install('$NS_DIST_DIR/docs', Dir('html'))
    docservices_common_env.Clean('Doxygen_html', Dir('html'))
    docservices_common_env.Depends(returnValue, generateDocs)

Return('returnValue')
