# Copyright (c) 2013 - 2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('cpsenv')

if not cpsenv.has_key('_ALLJOYNCORE_'):
    cpsenv.Append(LIBS = ['alljoyn'])
    if cpsenv['BR'] == 'on' :
        brFile = cpsenv.subst('$DISTDIR') + '/cpp/lib/BundledRouter.o'
        cpsenv['brobj'] = File(brFile)
        cpsenv['ajrlib'] = 'ajrouter'
    if cpsenv['OS'] == 'openwrt':
        cpsenv.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

cpsenv['CPS_DISTDIR'] = cpsenv['DISTDIR'] + '/controlpanel'

cpsenv.Install('$CPS_DISTDIR/inc/alljoyn/controlpanel', cpsenv.Glob('inc/alljoyn/controlpanel/*.h'))
cpsenv.Install('$CPS_DISTDIR/lib', cpsenv.SConscript('src/SConscript', exports = ['cpsenv']))
if cpsenv['BUILD_SERVICES_SAMPLES'] == 'on':
    cpsenv.Install('$CPS_DISTDIR/bin', cpsenv.SConscript('samples/SConscript', exports = ['cpsenv']))

# Build docs
installDocs = cpsenv.SConscript('docs/SConscript', exports = ['cpsenv'])
cpsenv.Depends(installDocs, cpsenv.Glob('$CPS_DISTDIR/inc/alljoyn/controlpanel/*.h'));
