# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('config_env')

if config_env.has_key('_ALLJOYN_JAVA_'):
    config_env.Append(JAVACLASSPATH = [ str(config_env.File('$DISTDIR/java/jar/alljoyn.jar')),
                                        str(config_env.File('$DISTDIR/java/jar/alljoyn_about.jar')) ])
    config_env['dep_jars'] = [ '$DISTDIR/java/jar/alljoyn.jar',
                               '$DISTDIR/java/jar/alljoyn_about.jar' ]
else:
    config_env.Append(JAVACLASSPATH = [ str(config_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn.jar')),
                                        str(config_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn_about.jar')) ])
    config_env['dep_jars'] = [ ]

# Currently the java ConfigService directly and indirectly uses a lot of
# deprecated code, so we turn off deprecation warnings here. A single
# warning it still printed letting us know we are using deprecated code.
# This is better than 100s of warnings across the ConfigService code.
config_env.Append(JAVACFLAGS = ['-Xlint:-deprecation'])

jars = []
jars += config_env.SConscript('src/SConscript', exports = ['config_env']),

# Sample programs
jars += config_env.SConscript('samples/SConscript', exports = ['config_env'])

config_env.Install('$DISTDIR/java/jar', jars)
