# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('about_env')

if about_env['OS_CONF'] in ['linux', 'openwrt', 'windows']:
    local_env = about_env.Clone()

    local_env.Prepend(LIBS = ['alljoyn_about'])
    
    # even though we have deprecated the About Service code we still want to 
    # build the samples till the code is removed from the build tree.
    if local_env['OS_GROUP'] == 'posix':
        local_env.Append(CXXFLAGS = ['-Wno-deprecated-declarations'])

    if local_env['BR'] == 'on' and local_env.has_key('ajrlib'):
        # Build apps with bundled daemon support
        local_env.Prepend(LIBS = [local_env['ajrlib']])

    # Sample programs
    sample_dirs = [
        'AboutClientSample',
        'AboutServiceSample'
        ]

    exports = { 'env': local_env}
    progs = [ local_env.SConscript('%s/SConscript' % sampleapp, exports = exports) for sampleapp in sample_dirs ]

else:
    progs = []

Return('progs')
