# Copyright (c) 2013-2014, AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('env', 'cobjs')
local_env = env.Clone()

srcs = ['ACServerSample.cc']
objs = local_env.Object(srcs)                      
objs.extend(cobjs)

if '_CONFIG_' in local_env["CPPDEFINES"] :
    configSrcs = 'ConfigServiceListenerImpl.cc'
    configObjs = local_env.Object(configSrcs)                      
    objs.extend(configObjs)

if '_CONTROLPANEL_' in local_env["CPPDEFINES"] : 
    local_env.Append(CPPPATH = local_env.Dir('generated').srcnode())
    local_env.Append(CPPPATH = local_env.Dir('provided').srcnode())

    genobjs = local_env.SConscript('generated/SConscript', {'env': local_env})
    providedobjs = local_env.SConscript('provided/SConscript', {'env': local_env})
   
    objs.extend(genobjs)
    objs.extend(providedobjs)
    
if '_ONBOARDING_' in local_env["CPPDEFINES"] :
    onboardingSrcs = 'OnboardingControllerImpl.cc'
    onboardingObjs = local_env.Object(onboardingSrcs)                      
    objs.extend(onboardingObjs)

prog = local_env.Program('ACServerSample', objs)

Return('prog')
