# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
# 
import os

Import('env')

clientDistDir = '$CPP_DISTDIR/samples/eventaction'

enaEnv = env.Clone()

# Install sample source
if enaEnv['OS'] == 'android':
    enaEnv.Install(clientDistDir + '/Android', 'Android/AndroidManifest.xml')
    enaEnv.Install(clientDistDir + '/Android', 'Android/.classpath')
    enaEnv.Install(clientDistDir + '/Android', 'Android/.project')
    enaEnv.Install(clientDistDir + '/Android', 'Android/project.properties')
    enaEnv.Install(clientDistDir + '/Android', enaEnv.Dir('Android/jni').srcnode())
    enaEnv.Install(clientDistDir + '/Android', enaEnv.Dir('Android/src').srcnode())
    enaEnv.Install(clientDistDir + '/Android', enaEnv.Dir('Android/res').srcnode())

# This sample depends on the About Service
if enaEnv['OS'] in ['linux', 'darwin', 'openwrt']:
    enaEnv.Append(CPPPATH = [ enaEnv.Dir('$CPP_DISTDIR/../about/inc') ])
    enaEnv.Append(LIBPATH = [ enaEnv.Dir('$CPP_DISTDIR/../about/lib') ])

    enaEnv.Prepend(LIBS = ['alljoyn_about'])
    ruleSrcFiles = enaEnv.Glob('SimpleRulesEngine/*.cc')
    ruleSrcFiles += enaEnv.Glob('SimpleRulesEngine/posix/*.cc')
    enaEnv.Program('sample_rule_app', ruleSrcFiles)
    enaEnv.Install('$CPP_DISTDIR/bin/samples', ['sample_rule_app'] )
