# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.
#

Import('env')
clientDistDir = '$DISTDIR/cpp/samples/TrustedTLSampleRN'

# Program binary
prog = [ env.Program('TrustedTLSampleRN', 'TrustedTLSampleRN.cc') ]

# The Trusted Thin Library Sample Routing Node binary is intended to be used
# by thin library apps and is packaged with the Thin Library SDK (Win7/Linux).
# It sets credentials so that thin library apps may connect to it in a trusted
# manner.  The fact that the program sets credentials implies a bundled router
# configuration.

if env['BR'] == 'on' and env['OS'] in ['linux', 'win7', 'win10' ]:
    env.Install('$DISTDIR/cpp/bin/samples', prog )
    env.Install(clientDistDir, env.Glob('*.cc'))
