# Copyright AllSeen Alliance. All rights reserved.
#
#    Contributed by Qualcomm Connected Experiences, Inc.,
#    with authorization from the AllSeen Alliance, Inc.
#    
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    
#        http://www.apache.org/licenses/LICENSE-2.0
#    
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    
#    Pursuant to Section 1 of the License, the work of authorship constituting
#    a Work and any Contribution incorporated in the Work shall mean only that
#    Contributor's code submissions authored by that Contributor.  Any rights
#    granted under the License are conditioned upon acceptance of these
#    clarifications.

Import('about_env')

if not about_env.has_key('_ALLJOYNCORE_'):
    about_env.Append(LIBS = ['alljoyn'])
    if about_env['BR'] == 'on' :
        about_env.Prepend(LIBS = ['ajrouter'])
    if about_env['OS'] == 'openwrt':
        about_env.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

# Make about dist a sub-directory of the alljoyn dist.  This avoids any conflicts with alljoyn dist targets.
about_env['ABOUT_DISTDIR'] = about_env['DISTDIR'] + '/cpp'

about_env.Install('$ABOUT_DISTDIR/inc/alljoyn/about', about_env.Glob('inc/alljoyn/about/*.h'))

# About libraries
about_env.Install('$ABOUT_DISTDIR/lib', about_env.SConscript('src/SConscript', exports = ['about_env']))

# Sample programs
about_env.Install('$ABOUT_DISTDIR/bin/samples', about_env.SConscript('samples/SConscript', exports = ['about_env']))

# only include command line samples, unit test, test programs if we are not 
# building for iOS. No support on iOS for command line applications.
if not (about_env['OS'] == 'darwin' and about_env['CPU'] in ['arm', 'armv7', 'armv7s', 'arm64',]):
    # Build unit Tests
    about_env.SConscript('unit_test/SConscript', exports = ['about_env'], variant_dir='$OBJDIR_ABOUT/unittest', duplicate = 0)
